os:
  - linux
  - osx
language: generic
sudo: required
dist: xenial

services:
  - mysql

env:
  global:
    - MYSQL_USER=test
    - MYSQL_PASSWORD=note
    - MYSQL_PORT=3306

osx_image: xcode9.3
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew tap vapor/tap;
      brew update;
      xcode-select --install
      bundle install --path vendor/bundle;
      brew install vapor;
      brew install cmysql;
      mysql.server start;
    else
      eval "$(curl -sL https://apt.vapor.sh)";
      sudo apt-get install vapor;
      sudo apt-get install cmysql;
      sudo chmod -R a+rx /usr/;
    fi
  - mysql -u root -e "set global max_connections = 1000";
  - mysql -u root -e "create database note_tests default character set utf8";
  - mysql -u root -e "create user 'test'@'localhost' IDENTIFIED BY 'note'";
  - mysql -u root -e "grant all on note_tests.* TO 'test'@'localhost'";

script:
  - swift build;
  - swift test;

after_success:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      swift package generate-xcodeproj;
      bundle exec fastlane send_coverage;
    fi
