name: Swift

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    
    runs-on: macos-latest
    
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: test
          MYSQL_PASSWORD: test

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: | 
        mysql -u root -e "set global max_connections = 1000"
        mysql -u root -e "create database yubatake_tests default character set utf8"
        mysql -u root -e "create database schema_check default character set utf8"
